<?php
use App\Components\Assets;
echo Phalcon\Tag::getTitle();
echo Assets::getInstance()->renderCollection('backendHeadScript', 'css');
?>
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<?php echo Assets::getInstance()->renderCollection('backendHeadScriptIE', 'js'); ?>
<![endif]-->        