<?php 
use Phalcon\Tag;
?>

<?php echo Tag::linkTo(array('/backend/index/index', '<span class="logo-mini"><b>K</b>M</span><span class="logo-lg"><b>KissMovies</b></span>', 'class' => 'logo')); ?>

<nav class="navbar navbar-static-top" role="navigation">
	<a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
    </a>
	<div class="navbar-right">
		<ul class="nav navbar-nav">
			<li class="dropdown messages-menu">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					<i class="fa fa-envelope"></i>
					<span class="label label-success">4</span>
				</a>
			</li>
			
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					<i class="fa fa-globe"></i>
				</a>
				<ul class="dropdown-menu">
					<li><?php echo Tag::linkTo(array('/backend/index/changeLanguage?lang=en', Tag::image(array('/skin/common/img/flg-uk.png', 'class' => 'icon-flag', 'alt' => 'UK')).' '. $t->_('English'))) ?></li>
					<li><?php echo Tag::linkTo(array('/backend/index/changeLanguage?lang=ja', Tag::image(array('/skin/common/img/flg-ja.png', 'class' => 'icon-flag', 'alt' => 'JA')).' '. $t->_('Japanese'))) ?></li>
				</ul>
			</li>
			
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					<i class="glyphicon glyphicon-user"></i>
					<span><?php echo $this->session->auth['fullname'] ?> <i class="caret"></i></span>
				</a>
				<ul class="dropdown-menu">
					<li><?php echo Tag::linkTo(array('/backend/auth/changePassword', '<i class="fa fa-lock"></i> '. $t->_('Change Password'), 'class' => '')); ?></li>
					<li><?php echo Tag::linkTo(array('/backend/auth/logout', '<i class="fa fa-sign-out"></i> '. $t->_('Sign Out'), 'class' => '')) ?></li>
				</ul>
			</li>
		</ul>
	</div>
</nav>