<ol class="breadcrumb">
    <li>
        <a href="/backend/index/index"><?php echo $t->_('Dashboard')?></a>
    </li>
    <li class="active">
        <?php echo $t->_('backend_breadcrumb_'.$this->router->getControllerName());?>
    </li>
    <?php 
//         use OE\Helper\Breadcrumb;
        
//         $param = array(
//                 'main-menu-backend'=> array(
//                         array(
//                                 'label' => 'Dashboard',
//                                 'controller' => 'index',
//                                 'action'=> 'index',
//                                 'url'   => '',
//                                 'pull-left'=> 'fa fa-dashboard',
//                                 'pull-right'=> '<small class="badge pull-right bg-green"> New </small>',
//                                 'pages' => array(
//                                         array(
//                                                 'label' => 'Dashboard',
//                                                 'controller' => 'index',
//                                                 'action'=> 'index',
//                                                 'url'   => '',
//                                                 'pull-left'=> 'fa fa-dashboard',
//                                                 'pull-right'=> '<small class="badge pull-right bg-green"> New </small>',
//                                         ),
//                                         array(
//                                                 'label' => 'Dashboard',
//                                                 'controller' => 'index',
//                                                 'action'=> 'contact',
//                                                 'url'   => '',
//                                                 'pull-left'=> 'fa fa-dashboard',
//                                                 'pull-right'=> '<small class="badge pull-right bg-green"> New </small>',
//                                         )
//                                 )
//                         ),
//                         array(
//                                 'label' => 'Dashboard2',
//                                 'controller' => 'test',
//                                 'action'=> 'index',
//                                 'url'   => '',
//                                 'pull-left'=> 'fa fa-dashboard',
//                                 'pull-right'=> '<small class="badge pull-right bg-green"> New </small>',
//                         ),
        
//                 ),
//         );
        
//         $breadCrumb = new Breadcrumb();
//         echo $breadCrumb->renderBreadcrumb($param['main-menu-backend']);
    ?>
</ol>