<?php

/**
 * Local variables
 * @var \Phalcon\Mvc\View\Engine $this
 */

?>
<?php echo $this->getContent() ?>

<h1>Edit Models</h1>

<ul class='menus'>
    <?php foreach($modules as $key=>$val) :?>
    <li class="<?php if(strcmp($key, $curModule) == 0) { echo "active";}?>">
        <a href="/webtools.php?_url=/models/list&module=<?php echo $key;?>">
            <?php echo $val?>
        </a>
    </li>
    <?php endforeach;?>
</ul>
<table class="table table-bordered table-striped">
	<thead>
		<tr>
			<td><b>Name</b></td>
			<td><b>Size</b></td>
			<td></td>
		</tr>
	</thead>
	<tbody>
	<?php
		$iterator = new DirectoryIterator($modelsDir[$curModule]);
		foreach($iterator as $fileinfo){
			if(!$fileinfo->isDot() && !$fileinfo->isDir()){
				echo '<tr>
					<td>', $fileinfo->getFileName(), '</td>
					<td>', $fileinfo->getSize(), '</td>
					<td><a href="', $this->url->get("webtools.php?_url=/models/edit/".$fileinfo->getFileName().'&module='.$curModule), '"
					    class"="btn">Edit</a></td>
				</tr>';
			}
		}
	?>
	</tbody>
</table>
