<!DOCTYPE html>
<html class="bg-black" style="background:#000 !important">
<head>
    <meta charset="UTF-8">
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <?php echo $this->partial('../layouts/partials/login/head');  ?>
</head>
<body class="bg-black" style="background:#000 !important">

<div class="main-content">
	<?php echo $this->getContent(); ?>                  	
</div>

<?php echo $this->partial('../layouts/partials/login/footer'); ?>
<script>
	$(function() {
		$('#username').focus();
	});
</script>
</body>
</html>