<?php 
use App\Helpers\FlashMessage;
$collapsed = $this->session->get('collapsed');
$collapsed = $this->request->get('view-mode') == 'full' ? true : $collapsed; 
?>
<!DOCTYPE html>
<html>
	<head>
        <meta charset="UTF-8">
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <?php echo $this->partial($layoutDir . '/partials/head');  ?>
        <?php echo $this->assets->outputCss(); ?>
        <?php echo $this->assets->outputJs(); ?>
        <script> var baseUri = '<?php echo $this->url->getBaseUri(); ?>' </script>
    </head>
    <body class="skin-black fixed">
        <!-- header logo: style can be found in header.less -->
        <header class="header">
            <?php echo $this->partial($layoutDir . '/partials/header'); ?>
        </header>
        
        <div class="wrapper row-offcanvas row-offcanvas-left">
            <!-- Left side column. contains the logo and sidebar -->
            <aside class="left-side sidebar-offcanvas <?php if($collapsed) echo 'collapse-left'; ?>">
	            <?php echo $this->partial($layoutDir . '/partials/aside'); ?>
            </aside>

            <!-- Right side column. Contains the navbar and content of the page -->
            <aside class="right-side <?php if($collapsed) echo 'strech'; ?>">
                <!-- Content Header (Page header) -->
                <section class="content-header">
                    <h1><?php echo $pageTitle ?></h1>
                    <?php echo $this->partial($layoutDir . '/partials/breadcrumb'); ?>
                </section>
                
                <!-- Flash message box -->
                <section class="message-box">
	                <?php $fm = new FlashMessage(); echo $fm->output(); ?>
                </section>

                <!-- Main content -->
                <section class="content">
                	<?php echo $this->getContent(); ?>
				</section><!-- /.content -->
            </aside><!-- /.right-side -->
        </div><!-- ./wrapper -->

        <?php echo $this->partial($layoutDir . '/partials/footer'); ?>
    </body>
</html>